config/routes.rb
Rails.application.routes.draw do
  get 'dashboard' => 'dashboards#index', as: :dashboard
  get 'home' => 'dashboards#home', as: :home

  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy', as: :logout

  # oauth
  get 'auth/twitter/callback', to: 'sessions#twitter', as: :twitter_auth
  get 'auth/failure', to: 'sessions#failure'

  resources :users, only: [:new, :show, :create]
  get '/settings' => 'settings#index', as: :settings
  post '/settings' => 'settings#update'
  post '/settings/new_api' => 'settings#new_api', as: :new_api

  resources :links, only: [:create, :show, :redirection, :destroy]

  get '/:id' => 'links#redirection', as: :redirect_url

  # api
  namespace :api do
    namespace :v1 do
      get 'links/create'
      get 'links/show'
      get 'users/show'
    end
  end

  root 'sessions#direct'
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  include SessionsHelper

  before_action :authentication_required
  before_action :get_settings, only: [:index, :new_api]

  def index
  end

  def update
    @settings = current_user
    if @settings.update_attributes(settings_params)
      SettingsMailer.update_email(@settings).deliver_now
      redirect_to settings_url, notice: "Successfully updated settings"
    else
      redirect_to settings_url, alert: "Failed to update settings"
    end
  end

  def new_api
    @settings.generate_api_key
    @settings.save
    redirect_to settings_url, notice: "You now have a new API key."
  end

  private

    def get_settings
      @settings = current_user
    end

    def settings_params
      params.require(:settings).permit(:name, :email)
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/index.html.erb
<div class="settings form">
  <div class="col-lg-offset-2 col-lg-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title text-center">Settings</h3>
      </div>
      <div class="panel-body">
        <%= form_for :settings, html: { class: 'form-horizontal' } do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control input-lg" %>
          </div>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: "form-control input-lg" %>
          </div>
          <div class="actions">
            <%= f.submit "Update", class: "btn-lg btn-primary btn-block" %>
          </div>
        <% end %>
        <br />
        <% if current_user.uid.nil? %>
          <%= button_to "Link Twitter Account", "auth/twitter", class: "btn-lg btn-info btn-block" %>
        <% end %>
        <br>
        <% if current_user.api_key.nil? %>
          <%= button_to "Create API Key", new_api_path, class: "btn-lg btn-info btn-block" %>
         <% else %>
           <%= button_to "Regenerate API Key", new_api_path, class: "btn-lg btn-info btn-block", data: {confirm: "Are you sure?  This will obsolete previous keys."} %>
        <% end %>
      </div>
      <div class="panel-body">
        <h4 class="text-center">To use with other apps</h4>
        <h6 class="text-center">Copy & Paste the following into your app:</h6>
        <pre class="text-center">http://localhost:3000/api/v1/links/create?api_key=<%= @settings.api_key %>&url=%@</pre>
      </div>
      <br />
    </div>
  </div>
</div>