config/routes.rb
Rails.application.routes.draw do
  get 'dashboard' => 'dashboards#index', as: :dashboard
  get 'home' => 'dashboards#home', as: :home

  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy', as: :logout

  # oauth
  get 'auth/twitter/callback', to: 'sessions#twitter', as: :twitter_auth
  get 'auth/failure', to: 'sessions#failure'

  resources :users, only: [:new, :show, :create]
  get '/settings' => 'settings#index', as: :settings
  post '/settings' => 'settings#update'
  post '/settings/new_api' => 'settings#new_api', as: :new_api

  resources :links, only: [:create, :show, :redirection, :destroy]

  get '/:id' => 'links#redirection', as: :redirect_url

  # api
  namespace :api do
    namespace :v1 do
      get 'links/create'
      get 'links/show'
      get 'users/show'
    end
  end

  root 'sessions#direct'
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  include SessionsHelper
  include LinksHelper

  def index
    @links = current_user.links.reject { |l| l.short_url.blank? }
    @link = current_user.links.build
  end

  def home
    @link = Link.new
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_shorten.html.erb
<div class="container">
  <div id="shorten">
    <div class="col-md-offset-2 col-md-7">
      <h1 class="text-center">MAKE YOUR LINKS COUNT!</h1>
      <div class="panel panel-default">
        <div class="panel-body">
          <%= form_for link, html: { class: 'form-inline' } do |f| %>
            <div class="form-group col-xs-8">
              <%= f.url_field :long_url, id: "long_url", class: 'form-control input-lg short-link' %>
            </div>
            <div class="form-group col-xs-4">
              <%= f.submit "Shorten It!", class: 'btn-lg btn-primary pull-right' %>
            </div>
            <% if signed_in_through_twitter? %>
              <div class="form-group col-xs-6">
                <%= f.check_box :tweet %>
                <%= f.label "Tweet this link!" %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/home.html.erb
<div class="container">
  <div id="home">
    <%= render partial: 'shorten', locals: { link: @link } %>
  </div>
</div>

app/views/dashboards/index.html.erb
<div class="container">
  <div id="home">
    <%= render partial: 'shorten', locals: { link: @link } %>
  </div>
</div>
<table id="link_table" class="table table-striped table-bordered table-responsive">
  <thead>
    <tr>
      <th>Clicks</th>
      <th>URL</th>
      <th>Shortened</th>
    </tr>
  </thead>
  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.clicks %></td>
        <td><%= link.long_url %></td>
        <td><%= link_to full_url(link), link_path(link.short_url) %></td>
      </tr>
    <% end %>
  </tbody>
</table>