config/routes.rb
Rails.application.routes.draw do
  get 'dashboard' => 'dashboards#index', as: :dashboard
  get 'home' => 'dashboards#home', as: :home

  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy', as: :logout

  # oauth
  get 'auth/twitter/callback', to: 'sessions#twitter', as: :twitter_auth
  get 'auth/failure', to: 'sessions#failure'

  resources :users, only: [:new, :show, :create]
  get '/settings' => 'settings#index', as: :settings
  post '/settings' => 'settings#update'
  post '/settings/new_api' => 'settings#new_api', as: :new_api

  resources :links, only: [:create, :show, :redirection, :destroy]

  get '/:id' => 'links#redirection', as: :redirect_url

  # api
  namespace :api do
    namespace :v1 do
      get 'links/create'
      get 'links/show'
      get 'users/show'
    end
  end

  root 'sessions#direct'
end

app/views/layouts/_errors.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %>">
      <%= msg %>
    </div>
  <% end %>
</div>

app/views/layouts/_nav.html.erb
<header class="navbar navbar-fixed-top navbar-default" id="top" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#desk-nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Shortener", root_path, class: "navbar-brand" %>
    </div>
    <nav class="collapse navbar-collapse" id="desk-nav-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
          <li><%= link_to "DASHBOARD", dashboard_path %></li>
          <li><%= link_to "SETTINGS", settings_path %></li>
          <li><%= link_to "LOGOUT", logout_path %></li>
        <% else %>
          <li><%= link_to "SIGN IN", login_path %></li>
          <li><%= link_to "SIGN UP", new_user_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shortener</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <%= render 'layouts/nav' %>

  <%= render 'layouts/errors' %>

  <div class="container">
    <div class="row">
      <%= yield %>
    </div>
  </div>
</body>
</html>